/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedCasesIndexRouteImport } from './routes/_authenticated/cases.index'
import { Route as AuthenticatedNotificationsNotificationIdRouteImport } from './routes/_authenticated/notifications.$notificationId'
import { Route as AuthenticatedCasesNewRouteImport } from './routes/_authenticated/cases_.new'
import { Route as AuthenticatedCasesCaseIdRouteImport } from './routes/_authenticated/cases.$caseId'
import { Route as AuthenticatedCasesCaseIdGenerateRouteImport } from './routes/_authenticated/cases.$caseId.generate'
import { Route as AuthenticatedCasesCaseIdDocumentsDocIdRouteImport } from './routes/_authenticated/cases.$caseId.documents.$docId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesIndexRoute = AuthenticatedCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsNotificationIdRoute =
  AuthenticatedNotificationsNotificationIdRouteImport.update({
    id: '/$notificationId',
    path: '/$notificationId',
    getParentRoute: () => AuthenticatedNotificationsRoute,
  } as any)
const AuthenticatedCasesNewRoute = AuthenticatedCasesNewRouteImport.update({
  id: '/cases_/new',
  path: '/cases/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesCaseIdRoute =
  AuthenticatedCasesCaseIdRouteImport.update({
    id: '/cases/$caseId',
    path: '/cases/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCasesCaseIdGenerateRoute =
  AuthenticatedCasesCaseIdGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => AuthenticatedCasesCaseIdRoute,
  } as any)
const AuthenticatedCasesCaseIdDocumentsDocIdRoute =
  AuthenticatedCasesCaseIdDocumentsDocIdRouteImport.update({
    id: '/documents/$docId',
    path: '/documents/$docId',
    getParentRoute: () => AuthenticatedCasesCaseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/get-started': typeof GetStartedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/ai': typeof AuthenticatedAiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRoute
  '/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/api/chat': typeof ApiChatRoute
  '/cases/$caseId': typeof AuthenticatedCasesCaseIdRouteWithChildren
  '/cases/new': typeof AuthenticatedCasesNewRoute
  '/notifications/$notificationId': typeof AuthenticatedNotificationsNotificationIdRoute
  '/cases/': typeof AuthenticatedCasesIndexRoute
  '/cases/$caseId/generate': typeof AuthenticatedCasesCaseIdGenerateRoute
  '/cases/$caseId/documents/$docId': typeof AuthenticatedCasesCaseIdDocumentsDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/get-started': typeof GetStartedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/ai': typeof AuthenticatedAiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRoute
  '/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/api/chat': typeof ApiChatRoute
  '/cases/$caseId': typeof AuthenticatedCasesCaseIdRouteWithChildren
  '/cases/new': typeof AuthenticatedCasesNewRoute
  '/notifications/$notificationId': typeof AuthenticatedNotificationsNotificationIdRoute
  '/cases': typeof AuthenticatedCasesIndexRoute
  '/cases/$caseId/generate': typeof AuthenticatedCasesCaseIdGenerateRoute
  '/cases/$caseId/documents/$docId': typeof AuthenticatedCasesCaseIdDocumentsDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/get-started': typeof GetStartedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/cases/$caseId': typeof AuthenticatedCasesCaseIdRouteWithChildren
  '/_authenticated/cases_/new': typeof AuthenticatedCasesNewRoute
  '/_authenticated/notifications/$notificationId': typeof AuthenticatedNotificationsNotificationIdRoute
  '/_authenticated/cases/': typeof AuthenticatedCasesIndexRoute
  '/_authenticated/cases/$caseId/generate': typeof AuthenticatedCasesCaseIdGenerateRoute
  '/_authenticated/cases/$caseId/documents/$docId': typeof AuthenticatedCasesCaseIdDocumentsDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/get-started'
    | '/sitemap.xml'
    | '/account'
    | '/ai'
    | '/dashboard'
    | '/events'
    | '/notifications'
    | '/onboarding'
    | '/resources'
    | '/api/chat'
    | '/cases/$caseId'
    | '/cases/new'
    | '/notifications/$notificationId'
    | '/cases/'
    | '/cases/$caseId/generate'
    | '/cases/$caseId/documents/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/get-started'
    | '/sitemap.xml'
    | '/account'
    | '/ai'
    | '/dashboard'
    | '/events'
    | '/notifications'
    | '/onboarding'
    | '/resources'
    | '/api/chat'
    | '/cases/$caseId'
    | '/cases/new'
    | '/notifications/$notificationId'
    | '/cases'
    | '/cases/$caseId/generate'
    | '/cases/$caseId/documents/$docId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/get-started'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/ai'
    | '/_authenticated/dashboard'
    | '/_authenticated/events'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/resources'
    | '/api/chat'
    | '/_authenticated/cases/$caseId'
    | '/_authenticated/cases_/new'
    | '/_authenticated/notifications/$notificationId'
    | '/_authenticated/cases/'
    | '/_authenticated/cases/$caseId/generate'
    | '/_authenticated/cases/$caseId/documents/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GetStartedRoute: typeof GetStartedRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases/': {
      id: '/_authenticated/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AuthenticatedCasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/$notificationId': {
      id: '/_authenticated/notifications/$notificationId'
      path: '/$notificationId'
      fullPath: '/notifications/$notificationId'
      preLoaderRoute: typeof AuthenticatedNotificationsNotificationIdRouteImport
      parentRoute: typeof AuthenticatedNotificationsRoute
    }
    '/_authenticated/cases_/new': {
      id: '/_authenticated/cases_/new'
      path: '/cases/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof AuthenticatedCasesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases/$caseId': {
      id: '/_authenticated/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases/$caseId/generate': {
      id: '/_authenticated/cases/$caseId/generate'
      path: '/generate'
      fullPath: '/cases/$caseId/generate'
      preLoaderRoute: typeof AuthenticatedCasesCaseIdGenerateRouteImport
      parentRoute: typeof AuthenticatedCasesCaseIdRoute
    }
    '/_authenticated/cases/$caseId/documents/$docId': {
      id: '/_authenticated/cases/$caseId/documents/$docId'
      path: '/documents/$docId'
      fullPath: '/cases/$caseId/documents/$docId'
      preLoaderRoute: typeof AuthenticatedCasesCaseIdDocumentsDocIdRouteImport
      parentRoute: typeof AuthenticatedCasesCaseIdRoute
    }
  }
}

interface AuthenticatedNotificationsRouteChildren {
  AuthenticatedNotificationsNotificationIdRoute: typeof AuthenticatedNotificationsNotificationIdRoute
}

const AuthenticatedNotificationsRouteChildren: AuthenticatedNotificationsRouteChildren =
  {
    AuthenticatedNotificationsNotificationIdRoute:
      AuthenticatedNotificationsNotificationIdRoute,
  }

const AuthenticatedNotificationsRouteWithChildren =
  AuthenticatedNotificationsRoute._addFileChildren(
    AuthenticatedNotificationsRouteChildren,
  )

interface AuthenticatedCasesCaseIdRouteChildren {
  AuthenticatedCasesCaseIdGenerateRoute: typeof AuthenticatedCasesCaseIdGenerateRoute
  AuthenticatedCasesCaseIdDocumentsDocIdRoute: typeof AuthenticatedCasesCaseIdDocumentsDocIdRoute
}

const AuthenticatedCasesCaseIdRouteChildren: AuthenticatedCasesCaseIdRouteChildren =
  {
    AuthenticatedCasesCaseIdGenerateRoute:
      AuthenticatedCasesCaseIdGenerateRoute,
    AuthenticatedCasesCaseIdDocumentsDocIdRoute:
      AuthenticatedCasesCaseIdDocumentsDocIdRoute,
  }

const AuthenticatedCasesCaseIdRouteWithChildren =
  AuthenticatedCasesCaseIdRoute._addFileChildren(
    AuthenticatedCasesCaseIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedCasesCaseIdRoute: typeof AuthenticatedCasesCaseIdRouteWithChildren
  AuthenticatedCasesNewRoute: typeof AuthenticatedCasesNewRoute
  AuthenticatedCasesIndexRoute: typeof AuthenticatedCasesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedCasesCaseIdRoute: AuthenticatedCasesCaseIdRouteWithChildren,
  AuthenticatedCasesNewRoute: AuthenticatedCasesNewRoute,
  AuthenticatedCasesIndexRoute: AuthenticatedCasesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GetStartedRoute: GetStartedRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
